rules:
  - label: novas-funcionalidades
    types: [opened]
    pattern: 'feature/*'

  - label: correcao-de-bugs
    types: [opened]
    pattern: 'bugfix/*'

  - label: correcoes-urgentes
    types: [opened]
    pattern: 'hotfix/*'

  - label: preparacao-de-versao
    types: [opened]
    pattern: 'release/*'

  - label: atualizacao-de-documentacao
    types: [opened]
    pattern: 'docs/*'
