novas-funcionalidades:
  - types: [opened]
    pattern: '^(feature\/.+)'

correcao-de-bugs:
  - types: [opened]
    pattern: '^(bugfix\/.+)'

correcoes-urgentes:
  - types: [opened]
    pattern: '^(hotfix\/.+)'

preparacao-de-versao:
  - types: [opened]
    pattern: '^(release\/.+)'

atualizacao-de-documentacao:
  - types: [opened]
    pattern: '^(docs\/.+)'
