name: Pull Request Labeler
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Debugging Step
        run: |
          echo "This is a debug message"
          echo "Current directory: $(pwd)"
          echo "List files: $(ls -la)"
      
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
